INSERT INTO ITEM(id,name, description) VALUES (1,'ITEM1', 'DESC1')
INSERT INTO ITEM(id,name, description) VALUES (2,'ITEM2', 'DESC2')
INSERT INTO ITEM(id,name, description) VALUES (3,'ITEM3', 'DESC3')
INSERT INTO ITEM(id,name, description) VALUES (4,'ITEM4', 'DESC4')
INSERT INTO ITEM(id,name, description) VALUES (5,'ITEM5', 'DESC5')
